# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\x12\x04todo\"4\n\x11\x43reateTodoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"\x1d\n\x0fReadTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x12\n\x10ListTodosRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETODOREQUEST']._serialized_start=24
  _globals['_CREATETODOREQUEST']._serialized_end=76
  _globals['_READTODOREQUEST']._serialized_start=78
  _globals['_READTODOREQUEST']._serialized_end=107
  _globals['_UPDATETODOREQUEST']._serialized_start=109
  _globals['_UPDATETODOREQUEST']._serialized_end=173
  _globals['_DELETETODOREQUEST']._serialized_start=175
  _globals['_DELETETODOREQUEST']._serialized_end=206
  _globals['_LISTTODOSREQUEST']._serialized_start=208
  _globals['_LISTTODOSREQUEST']._serialized_end=226
# @@protoc_insertion_point(module_scope)
