# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: responses.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import definitions.todo_pb2 as todo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fresponses.proto\x12\x04todo\x1a\ntodo.proto\".\n\x12\x43reateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\",\n\x10ReadTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\".\n\x12UpdateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\".\n\x11ListTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'responses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETODORESPONSE']._serialized_start=37
  _globals['_CREATETODORESPONSE']._serialized_end=83
  _globals['_READTODORESPONSE']._serialized_start=85
  _globals['_READTODORESPONSE']._serialized_end=129
  _globals['_UPDATETODORESPONSE']._serialized_start=131
  _globals['_UPDATETODORESPONSE']._serialized_end=177
  _globals['_DELETETODORESPONSE']._serialized_start=179
  _globals['_DELETETODORESPONSE']._serialized_end=216
  _globals['_LISTTODOSRESPONSE']._serialized_start=218
  _globals['_LISTTODOSRESPONSE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
